# Generated by Django 6.1 on 2026-08-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0008_remove_transmission_name_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
