# Generated by Django 6.1 on 2026-08-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0009_transmission_lat_transmission_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uploaded at'),
        ),
    ]
